### ISSUE TITLE
Write a wiki page explaining Spacemesh consensus in context

### ISSUE THREAD

**Issue by avive** [spacemeshos/protocol#27]
We need to explain how the hare protocol is different than Hotstuff and why we chose it over Hotstuff. This is a common question by protocol researchers / dev looking at Spacemesh protocol for the first time.

See #28

# Resources

- Tendermint: https://arxiv.org/abs/1807.04938, https://tendermint.com/static/docs/tendermint.pdf, https://atrium.lib.uoguelph.ca/xmlui/handle/10214/9769
- HotStuff: https://arxiv.org/abs/1803.05069
- Chia: https://www.chia.net/faq/, https://www.chia.net/assets/ChiaGreenPaper.pdf, https://eprint.iacr.org/2017/893, https://eprint.iacr.org/2018/712.pdf

**Comment by lrettig** [comment]
Link to discussion about this today on Slack: https://spacemesh.slack.com/archives/CG91F13C7/p1582292484084200

**Comment by lrettig** [comment]
More from Slack:

> A common perception of the protocol is that it just uses POST for sybil-resistance instead of staked coins in PoStake systems, and that there are no real difference between HARE and other flavors of PBFT. Hence the question - why did the project choose HARE over HOTSTUFF (used in Libra) or Tendermint/Cosmos PBFT protocol? We need to explain the differences between HARE and these other PBFT protocols.
> We need a concise explanation about why we believe TORTOISE is needed for consensus beyond HARE and how Tortoise is related to POST. Nobody understands that.
> There are different explanations - depending who you ask in the research team - we need a good canonical answer to these questions
> even assuming the new paper explains this for researchers, we need an explanation for developers / crypto people who don’t have a phd in BFT
> l agree. This would be very helpful. Another thing in the same vein that would be helpful is a clear explanation of the differences among spacemesh, chia, and filecoin. I get asked this at literally every event. We need a canonical answer to this too

**Comment by lrettig** [comment]
I began to work on this in #28 but still have lots of questions and definitely still need help.

Questions:

- What would happen if we had only Tortoise? We'd lose efficiency but what would this mean in practice?
- Hare is based on [ADDNR18](https://eprint.iacr.org/2018/1028.pdf). What is Tortoise based on? I.e., what is its lineage? (Is the answer in [Meshcash](https://eprint.iacr.org/2017/300.pdf)?)
- Are we sure that HotStuff doesn't scale to thousands of nodes? (Libra is/was supposed to have thousands of independent validators.)
- Given lack of player replaceability, why aren't Tendermint/HotStuff chains including Cosmos and Libra worried about DoS attacks on future known validators? (Or what mitigations do they have in place?)
- According to Julian, if consensus fails in a BFT-style system even briefly, history can change and the system cannot recover from this ("if you are out of consensus for a second, you are out forever"). What happens _in practice_ in such a system in case of a failure? Is there mitigation at the social layer? Has this ever happened in practice?
- Julian: "We designed [the Hare] specifically to fit our algorithm. Other algorithms can’t do what Hare does, simply because we invented a new form of consensus that best fits our needs." What are these needs? What is it that other algorithms cannot do, that Hare can do?
- Do we want to talk about Tendermint as distinct from HotStuff? If so, what is the distinction?

Additionally, there are some differences between Spacemesh consensus and Chia and Filecoin, respectively, discussed in the protocol paper, but I think we can say more. Leaving this as a task for later.

**Comment by avive** [comment]
I would start more higher-level questions:
1. How does Hare different than Tendermint BFT and from HotStuff.
2. What are the main differences between the current iteration of the Chia protocol and the Spacemesh protocol?

**Comment by lrettig** [comment]
Had a great call on Friday with Tal and Julian and got answers to many of these questions. Thanks guys :) I updated #28 with my current understanding, based on that call and the notes I took. Here are my outstanding questions:

- Hare is based on ADDNR18. What is Tortoise based on? I.e., what is its lineage? (Is the answer in Meshcash?)
- Julian said that the max. participants in the Hare is ~800. How do we know that this will be enough for our needs, forever? What else does this parameter/limitation affect?
- Given lack of player replaceability, why aren't Tendermint/HotStuff chains including Cosmos and Libra worried about DoS attacks on future known validators? (Or what mitigations do they have in place?)
- Do we want to talk about Tendermint as distinct from HotStuff? If so, what is the distinction?
- What are the main differences between the current iteration of the Chia protocol and the Spacemesh protocol?

I also have a lot of beacon-related questions:

- What's the difference between the Tortoise beacon and the Hare beacon?
- How does each protocol use the beacon?
- How does the beacon work?
- How does self-healing rely on the beacon?
- What's the design of the beacon based on (i.e., any prior work)?

**Comment by lrettig** [comment]
Follow-up question from today's chat with @ilans: based on my conversation with Tal and Julian, I previously wrote:

> Efficiency: the self-healing protocol is less efficient (measured in terms of communication complexity: the number of messages passed) than the Hare. We have tuned the Hare to have the lowest possible communication complexity.

But Tortoise doesn't involve message-passing among nodes, does it? So why is this the case?

**Comment by lrettig** [comment]
Also:

> Robustness: while self-healing requires > 2/3 honest majority, the Hare requires only a simple honest majority, and depending on the size of the committee it can theoretically tolerate up to 2/3 malicious participants. This is because it takes advantage of strong synchrony assumptions.

Without Hare, is the network more vulnerable to attacks? If so, how? How would this play out in practice?

**Comment by lrettig** [comment]
How is the leader chosen in the Hare round 2? How does everyone agree on the leader?

**Comment by lrettig** [comment]
I updated the doc based on my most recent chats with Tal. I began to fill in a new section (at the very end) comparing Spacemesh to Chia and Filecoin. Tal explained some of the differences in Chia, which I've included, although I think this could be improved. I don't have anything on Filecoin yet, this still needs to be added.
